gettingstarted/urls.py
from django.conf.urls import include, url

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

from p2preview import urls as p2preview_urls

import p2preview.views

urlpatterns = [
    url(r'^', include(p2preview_urls.urlpatterns)),
    url(r'^admin/', include(admin.site.urls)),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

p2preview/urls.py
from django.conf.urls import include, url

from . import views
from . import apiUrls as api_urls

urlpatterns = [
    url(r'^', include(api_urls.urlpatterns)),
	url(r'^$', views.home),
    url(r'^login/$', views.login_page),
    url(r'^signUp/$', views.signUp_page),
    url(r'^course/$', views.course),
    url(r'^course/new/$', views.new_course_page),
    url(r'^criteria/$', views.criteria_page),
    url(r'^rubricTemplate/$', views.rubric_template),
    url(r'^statistics/$', views.statistics_page),
    url(r'^activity/$', views.activity),
    url(r'^activity/(?P<pk>[0-9]+)/$', views.activity_details),
]

p2preview/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=45, blank=False, default='')
    email = models.EmailField(blank=False, default='', unique=True)
    password = models.CharField(max_length=20, blank=False, default='')
    personType = models.IntegerField(blank=False)
    lastLogined = models.DateTimeField(auto_now_add=True)
    token = models.CharField(max_length=20, blank=True, default='')

    def __str__(self):
        return self.name

class Student(models.Model):
    sId = models.ForeignKey(Person, on_delete=models.CASCADE)
    rollNo = models.CharField(max_length=8, blank=False, default='')
    branch = models.CharField(max_length=5, blank=False, default='')

    def __str__(self):
        return self.sId.name + " " + self.rollNo

class Instrutor(models.Model):
    iId = models.ForeignKey(Person, on_delete=models.CASCADE)
    department = models.CharField(max_length=5, blank=False, default='')
    office = models.CharField(max_length=10, blank=False, default='')
    visitingHours = models.CharField(max_length=20, blank=False, default='')

    def __str__(self):
        return self.iId.name

class Course(models.Model):
    name = models.TextField(blank=False, default='')
    description = models.TextField(max_length=200, blank='True', default='')
    instructorId = models.ForeignKey(Instrutor, on_delete=models.CASCADE)
    code = models.CharField(max_length=20, blank=False, default='', unique=True)

    def __str__(self):
        return self.name

class RegisteredCourses(models.Model):
    courseId = models.ForeignKey(Course, on_delete=models.CASCADE)
    sId = models.ForeignKey(Student, on_delete=models.CASCADE)

class Rubric(models.Model):
    iId = models.ForeignKey(Instrutor, on_delete=models.CASCADE)
    name = models.CharField(max_length=30, blank=False, default='')
    lastModified = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Activity(models.Model):
    iId = models.ForeignKey(Instrutor, on_delete=models.CASCADE)
    courseId = models.ForeignKey(Course, on_delete=models.CASCADE)
    rubricId = models.ForeignKey(Rubric, on_delete=models.CASCADE)
    name = models.TextField(blank=False, default='')
    code = models.CharField(max_length=5, blank=False, default='')
    duration = models.IntegerField(blank=False)
    isActive = models.BooleanField(blank=False, default=False)
    groupSize = models.IntegerField(default=1)
    textOrImage = models.BooleanField(blank=False)

    def __str__(self):
        return self.name

class Group(models.Model):
    creationDate = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=10, blank=True, default='')

    def __str__(self):
        return self.name

class GroupDetail(models.Model):
    groupId = models.ForeignKey(Group, on_delete=models.CASCADE)
    sId = models.ForeignKey(Student, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('groupId', 'sId')

class Generic(models.Model):
    description = models.CharField(max_length=100, blank=False, default='')
    answer = models.IntegerField(blank=True)
    iId = models.ForeignKey(Instrutor, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

class GenericOption(models.Model):
    genericId = models.ForeignKey(Generic, on_delete=models.CASCADE)
    option = models.TextField(blank=False, default='')
    points = models.IntegerField(default=0)
    optionNo = models.IntegerField(default=0)

    class Meta:
        unique_together = ('genericId', 'optionNo')

class RegisteredGroupsForActivity(models.Model):
    groupId = models.ForeignKey(Group, on_delete=models.CASCADE)
    assigmentPk = models.IntegerField()
    activityId = models.ForeignKey(Activity, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('groupId', 'assigmentPk')

class Criteria(models.Model):
    rubricId = models.ForeignKey(Rubric, on_delete=models.CASCADE)
    genericId = models.ForeignKey(Generic, on_delete=models.CASCADE)

    def __str__(self):
        return self.rubricId.name + " " + self.genericId.description

    class Meta:
        unique_together = ('rubricId', 'genericId')

class Response(models.Model):
    registeredGroup = models.ForeignKey(RegisteredGroupsForActivity, on_delete=models.CASCADE)
    criteria = models.ForeignKey(Criteria, on_delete=models.CASCADE)
    response = models.CharField(max_length=1, blank=False, default='')
    comment = models.CharField(max_length=30, blank=True, default='', null=True)
    time = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('registeredGroup', 'criteria')

class UploadFile(models.Model):
    file = models.ImageField(upload_to='static/p2preview/files')

class ActivityImageAssigment(models.Model):
    fileURL = models.CharField(max_length=5000, blank=False, default='')
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    groupId = models.TextField(blank=True, default='', null=True)
    count = models.IntegerField(default=0, blank=True)

class ActivityAssigment(models.Model):
    text = models.CharField(max_length=5000, blank=False, default='')
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    groupId = models.TextField(blank=True, default='', null=True)
    count = models.IntegerField(default=0, blank=True)

p2preview/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db.models import Min
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.shortcuts import render, render_to_response
from django.template import loader
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from p2preview.models import Person, Student, Instrutor, Course, RegisteredCourses, GroupDetail, Group, Activity, RegisteredGroupsForActivity, Criteria, GenericOption, Response, Rubric, Generic, UploadFile, ActivityAssigment, ActivityImageAssigment

import string
import random
import ast

@require_http_methods(["GET"])
@csrf_exempt
def fetch_self(request):
    person = validatePerson(request.META['HTTP_TOKEN'])
    if person != -1:
        if person[0].personType == 1:
            instrutor = Instrutor.objects.filter(iId=person[0])
            data = {
                'success': 1,
                'message': '',
                'self': {
                    'name': person[0].name,
                    'email': person[0].email,
                }
            }
        elif person[0].personType == 2:
            student = Student.objects.filter(sId=person[0])
            data = {
                'success': 1,
                'message': '',
                'self': {
                    'name': person[0].name,
                    'email': person[0].email,
                    'rollNo': student[0].rollNo,
                    'branch': student[0].branch,
                }
            }
    else:
        data = {
            'success': -99,
            'message': 'Please login again',
        }
    return JsonResponse(data, safe=True)


# Create your views here.
@csrf_exempt
def home(request):
    instrutor = validateInstructor(request.COOKIES.get('token'))
    if instrutor != -1:
        template = loader.get_template('p2preview/home.html')
        context = {
            'course_count': Course.objects.filter(instructorId=instrutor).count(),
            'activity_count': Activity.objects.filter(iId=instrutor).count(),
            'rubric_count': Rubric.objects.filter(iId=instrutor).count(),
            'criteria_count' : Generic.objects.filter(iId=instrutor).count(),
        }
        return HttpResponse(template.render(context, request))
    else:
        return redirectToLogin()

@csrf_exempt
def activity_details(request, pk):
    instrutor = validateInstructor(request.COOKIES.get('token'))
    if instrutor != -1:
        activity = Activity.objects.filter(pk=pk, iId=instrutor[0])
        if (activity.count() == 1):
            """get all assigment"""
            if activity[0].textOrImage:
                assigment = ActivityAssigment.objects.filter(activity=activity[0])
            else:
                assigment = ActivityImageAssigment.objects.filter(activity=activity[0])


            criterias_data = Criteria.objects.filter(rubricId=activity[0].rubricId)
            graphActivies = []
            for assig in assigment:
                """get criterias of the activity"""
                criterias = []
                registeredGroup = RegisteredGroupsForActivity.objects.filter(activityId=activity[0], assigmentPk=assig.pk).order_by('-pk')
                for criteria in criterias_data:
                    series = []
                    genericOptions = GenericOption.objects.filter(genericId=criteria.genericId)
                    totalAttempt = 0
                    for gen in genericOptions:
                        count = 0
                        totalCount = registeredGroup.count()
                        for rg in registeredGroup:
                            count = count + Response.objects.filter(registeredGroup=rg, criteria=criteria, response=gen.optionNo).count()
                            # totalCount = totalCount + Response.objects.filter(registeredGroup=rg, criteria=criteria).count()
                        if totalCount != 0:
                            totalAttempt += count
                            series.append({
                                str('name'): str(gen.option),
                                str('data'): (count*100)/totalCount,
                            })
                    if totalCount != 0:
                        series.append({
                            str('name'): str('Unattempted'),
                            str('data'): ((totalCount-totalAttempt)*100)/totalCount,
                        })

                        criterias.append({
                            str('criteria'): str(criteria.genericId.description),
                            str('criteria_id'): str(criteria.pk),
                            str('series'): list(series),
                            })

                graphActivies.append({
                    str('criterias'): criterias,
                    str('groupId'): str(),
                    str('assigId'): assig.pk,
                })



            """for individual"""
            individual = []
            registeredGroup = RegisteredGroupsForActivity.objects.filter(activityId=activity[0]).order_by('-pk')
            for rg in registeredGroup:
                responses = Response.objects.filter(registeredGroup=rg)
                criterias_data = []
                responses_data = []
                points = 0
                for res in responses:
                    criterias_data.append(res.criteria)
                    try:
                        generic = GenericOption.objects.filter(genericId=res.criteria.genericId, optionNo=res.response)
                        if (generic.count() == 1):
                            points += generic[0].points
                            responses_data.append({
                                'response': generic[0].option,
                                'comment': res.comment,
                                'criteria': res.criteria,
                            })
                    except:
                        points = points + 0
                        responses_data.append({
                            'response': 'Unattempted',
                            'comment': res.comment,
                            'criteria': res.criteria,
                        })

                if activity[0].textOrImage:
                    assigment = ActivityAssigment.objects.get(pk=rg.assigmentPk)
                else:
                    assigment = ActivityImageAssigment.objects.get(pk=rg.assigmentPk)
                individual.append({
                    'reviewOf': assigment,
                    'reviewBy': {
                        'groupId': rg.groupId.pk,
                        'groupName': rg.groupId.name,
                        'groupMembers': get_group_members(rg.groupId),
                    },
                    'criterias': criterias_data,
                    'responses': responses_data,
                    'points': points,
                })

            template = loader.get_template('p2preview/statistics.html')
            context = {
                'assigments': graphActivies,
                'individual': individual,
                'activity': activity[0],
                'total_points': get_total_points_for_activity(activity[0])
            }
            return HttpResponse(template.render(context, request))
        else:
            """redirect to /activity"""
            response = HttpResponseRedirect('/activity')
            response.delete_cookie('token')
            return response

    else:
        return redirectToLogin()

def get_total_points_for_activity(activity):
    points = 0
    criterias = Criteria.objects.filter(rubricId=activity.rubricId)
    for criteria in criterias:
        genericOptions = GenericOption.objects.filter(genericId=criteria.genericId)
        maximum_points = 0
        for genericOpt in genericOptions:
            if genericOpt.points > maximum_points:
                maximum_points = genericOpt.points
        points += maximum_points

    return points

def activity(request):
    instrutor = validateInstructor(request.COOKIES.get('token'))
    if instrutor != -1:
        template = loader.get_template('p2preview/activity.html')
        activities_data = Activity.objects.filter(iId=instrutor[0]).order_by('-pk')
        activities = []
        for activity in activities_data:
            if (activity.textOrImage):
                """fetch all text data"""
                assigments = ActivityAssigment.objects.filter(activity=activity)
            else:
                """fetch all text data"""
                assigments = ActivityImageAssigment.objects.filter(activity=activity)
            count = 0
            for assigment in assigments:
                count = count + RegisteredGroupsForActivity.objects.filter(assigmentPk=assigment.pk).count()
            activities.append({
                'activity': activity,
                'assigments': assigments,
                'groupsRegistered': count
            })

        context = {
            'rubrics': Rubric.objects.filter(iId=instrutor[0]),
            'courses': Course.objects.filter(instructorId=instrutor[0]),
            'activities': activities
        }
        return HttpResponse(template.render(context, request))
    else:
        return redirectToLogin()

@require_http_methods(["POST"])
@csrf_exempt
def toggle_activity_status(request):
    instrutor = validateInstructor(request.COOKIES.get('token'))
    if instrutor != -1:
        activity = Activity.objects.filter(pk=request.POST["activity_id"])
        if (activity.count() == 1):
            if (request.POST["value"] == 'True'):
                activity.update(isActive=True)
            else:
                activity.update(isActive=False)
            data = {
                'success': 1,
                'message': 'Successfully updated',
            }
        else:
            data = {
                'success': 0,

p2preview/templates/p2preview/base.html
<!DOCTYPE html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>{% block title %}{% endblock %} - P2PReview</title>

  {% load staticfiles %}

  <meta name="title" content="Peer Review System">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'p2preview/css/base.css' %}">

  {% block extrastyles %}{% endblock %}

  <link rel="shortcut icon" href="{% static 'p2preview/media/p2p.png' %}" type="image/x-icon">
  <link rel="icon" href="{% static 'p2preview/media/p2p.png' %}" type="image/x-icon">

  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

  {% block extrafonts %}{% endblock %}

</head>
  <body>
    <div class="navbar">
      <div class="navitem row container-fluid">
        <div class="emphasize col-md-3">
          <a href="/">Peer Review System</a>
        </div>
        <div class="col-md-auto">
          <a href="/course/">Courses</a>
        </div>
        <div class="col-md-auto">
          <a href="/criteria/">Criteria</a>
        </div>
        <div class="col-md-auto">
          <a href="/rubricTemplate">Rubric Template</a>
        </div>
        <div class="col-md-auto">
          <a href="/activity">Activity</a>
        </div>
        <div class="col" id="logined" ><!--align="right"-->
          <div class="dropdown show" >
            <a class="dropdown-toggle " role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">Hi!</a>
            <div class="dropdown-menu dropdown-menu-right loggedIn" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" id="editProfile" href="#">Edit Profile</a>
              <a class="dropdown-item" id="logout" onclick="logout()" href="#">Logout</a>
              <a class="dropdown-item" id="login" href="/login">Login</a>
              <a class="dropdown-item" id="signUp" href="/signUp">Register</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% block body %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'p2preview/js/bootstrap.min.js' %}"/>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/
    bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'p2preview/js/commonJs.js' %}" ></script>
    <script type="text/javascript" src="{% static 'p2preview/js/baseJs.js' %}" ></script>
    <script type="text/javascript"></script>
    {% block extrajavascripts %}
    {% endblock %}
  </body>
</html>

p2preview/templates/p2preview/course_new.html
{% extends './base.html' %}
{% block title %}New Course{% endblock %}

{% load staticfiles%}

{% block body %}
<body>
  <br>
  <br>
  <div class="container">

    <form id="newCourseForm" class="form-horizontal" action="/api/v1/create_course/" method="POST">
      <div class="row form-group">
        <label for="courseName" class="col-sm-2 control-label">Course Name</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" required autofocus id="id_course_name" placeholder="Software Engineering">
        </div>
      </div>
      <div class="row form-group">
        <label for="courseDescription" class="col-sm-2 control-label">Course Description</label>
        <div class="col-sm-10">
          <textarea type="text" class="form-control" id="id_course_description" rows="3" placeholder="Description"></textarea>
        </div>
      </div>
      <span id="id_error"></span>
      <div class="row form-group">
        <div class="col-md-offset-4 col-sm-10">
          <button type="submit" class="btn btn-default">Submit</button>
        </div>
      </div>
    </form>

  </div>

</body>
{% endblock %}
{% block extrajavascripts %}
  <script type="text/javascript" src="{% static 'p2preview/js/course_new.js' %}"/>
  <script>

  </script>
{% endblock %}

p2preview/templates/p2preview/criteria.html
{% extends './base.html' %}
{% block title %}Criteria{% endblock %}

{% load staticfiles%}

{% block extrastyles %}
    <link rel="stylesheet" type="text/css" href="{% static 'p2preview/css/criteria.css' %}"/>
{% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="row">
    <div class="col-auto ml-auto">
      <button type="button" class="btn btn-success add" data-toggle="modal" data-target="#exampleModal">
        Add Criteria
      </button>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      {% if criterias|length > 0 %}
      {% for criteria in criterias %}
      <div class="criteriaList">
        <div class="row criteria">
          <div class="col-sm-12">
            Criteria #{{ forloop.counter }} : <span class="heading"> {{ criteria.generic.description }}</span>
          </div>
        </div>
        {% for genric_option in criteria.generic_options %}
        <div class="row">
          <div class="col-sm-6">
            <b>Option #{{ forloop.counter }} : </b> {{ genric_option.option }}
          </div>
          <div class="col-sm-6">
            <b>Points : </b> {{ genric_option.points }}
          </div>
        </div>
        {% endfor %}
      </div>
      {% endfor %}
      {% else %}
      <div class="criteriaList">
        <div class="row criteria">
          <div class="col-sm-12">
            No criterias added yet, please add one!
          </div>
        </div>
      </div>
      {% endif %}

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Add Generic Criteria</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form id="#newCriteriaForm" method="post" action="/api/v1/create_generic/">
                <div class="form-group row">
                  <label for="Criteria" class="col-sm-2 col-form-label">Criteria</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" required id="id_description" placeholder="Criteria">
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-auto ml-auto">
                  <button type="button" class="optionAdd btn btn-success">Add Option</button>
                  </div>
                </div>
            </div>
            <span id="id_error"></span>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button id="submitButton" type="submit" class="btn btn-primary">Save changes</button>
              </form>
            </div>
          </div>
        </div>
      </div>

{% endblock %}
{% block extrajavascripts %}
  <script type="text/javascript">
  var optionNumber = 0;
$('.optionAdd').click(function() {
  var newEntity =
    '<div class="form-group row"><label for="option' +
    optionNumber +
    '" class="col-sm-2 col-form-label">Option ' +
    (optionNumber + 1) +
    '</label><div class="col-sm-8"><input required type="text" class="form-control" id="optionInput' +
    optionNumber +
    '" placeholder="Option ' +
    (optionNumber + 1) +
    '"></div><div class="col-sm-2"><input type="number" class="form-control" id="optionPoints' +
    optionNumber +
    '" placeholder="1-10"></div></div>';
  $('.modal-body').append(newEntity);
  optionNumber++;
});

$('#submitButton').click(function() {
  $('#id_error').text('');
  var frm = $('#newCriteriaForm');
  var description = $('#id_description').val();
  var answer = $('#answer').val();

  var options = [],
    points = [];

  var i = 0;

  if (description.length === 0) {
    alert('Please enter description');
    return false;
  }

  for (i = 0; i < optionNumber; i++) {
    var text = $('#optionInput' + i).val();
    if(text.length !== 0) {
      options = [...options, text];
      points = [...points, $('#optionPoints' + i).val() || 0];
    }
  }

  if(options.length === 0)
  {
    alert("Please enter at least one option");
    return false;
  }

  $.ajax({
    type: 'post',
    beforeSend: function(request) {
      request.setRequestHeader('TOKEN', getCookie('token'));
    },
    url: '/api/v1/create_generic/',
    data: {
      description: description,
      options: JSON.stringify(options),
      points: JSON.stringify(points),
      answer: -1,
    },
    dataType: 'json',
    success: function(data) {
      if (data.success === 1) {
        $(location).attr('href', '/criteria');
      } else if (data.success === -99) {
        clearLoginCookie();
      } else {
        $('#id_error').text(data.message);
      }
    },
  });
  return false;
});
</script>

{% endblock %}

p2preview/templates/p2preview/login.html
{% extends './base.html' %}
{% block title %}Login{% endblock %}

{% load staticfiles%}

{% block extrastyles %}
    <link rel="stylesheet" type="text/css" href="{% static 'p2preview/css/signin.css' %}"/>
{% endblock %}

{% block body %}
<body>
  <div class="container-fluid">

    <form id="signInForm" class="form-signin" action="/api/v1/login/" method="post">
      <h2 class="form-signin-heading">Please sign in</h2>
      <label for="inputEmail" class="sr-only">Email address</label>
      <input name="email" type="email" id="id_email" class="form-control" placeholder="Email address" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input name="password" type="password" id="id_password" class="form-control" placeholder="Password" required>
      <span id="id_error"></span>
      <!--<div class="checkbox">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>-->
      <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
      <div class="signup">
        <a href="/signUp">Not Registered yet, Click to Signup!</a>
      </div>
    </form>



  </div>
  
</body>
{% endblock %}
{% block extrajavascripts %}
  <script type="text/javascript" src="{% static 'p2preview/js/signin.js' %}"/>
  <script>

  </script>
{% endblock %}

p2preview/templates/p2preview/signup.html
{% extends './base.html' %}
{% block title %}Sign up{% endblock %}

{% load staticfiles%}

{% block extrastyles %}
    <link rel="stylesheet" type="text/css" href="{% static 'p2preview/css/signup.css' %}"/>
{% endblock %}

{% block body %}
<body>
  <div class="container">

    <form class="form-horizontal form-signup" id="signUpForm" role="form"
      action="signup" method="post" autocomplete="off">
      <h2 class="form-signin-heading">Please register</h2>
      <div class="form-group row">
        <label for="firstName" class="col-sm-3 col-form-label">
          Name
        </label>
        <div class="col-sm-9">
          <input id="id_name" type="text" name="firstName" placeholder="Name"
            class="form-control" maxlength="45" autofocus required>
        </div>
      </div>
      <div class="form-group row">
        <label for="username" class="col-sm-3 col-form-label">
          Email
        </label>
        <div class="col-sm-9">
          <input id="id_email" type="text" name="email" placeholder="Email"
            class="form-control" maxlength="50" required>
        </div>
      </div>
      <div class="form-group row">
        <label for="password" class="col-sm-3 col-form-label">
          Password
        </label>
        <div class="col-sm-9">
          <input id="id_password" type="password" name="password" placeholder="Password"
            class="form-control" maxlength="20" required>
        </div>
      </div>
      <div class="form-group row">
        <label for="department" class="col-sm-3 col-form-label">
          Department
        </label>
        <div class="col-sm-9">
          <select id="id_department" name="department" class="form-control">
            <option value="" selected disabled>Choose Department</option>
            <option value="CSE">Computer Science and Engineering</option>
            <option value="ECE">Electronics and Communication Engineering</option>
            <option value="MME">Mechanical and Mechatronics Engineering</option>
            <option value="Mathematics">Mathematics</option>
            <option value="Physics">Physics</option>
            <option value="HSS">Humanities and Social Sciences</option>
          </select>
        </div>
      </div>
      <div class="form-group row">
        <label for="officeNo" class="col-sm-3 col-form-label">
          Office No
        </label>
        <div class="col-sm-9">
          <input id="id_office" type="string" name="officeNo" placeholder="Office No"
            class="form-control" maxlength="10" autofocus required>
        </div>
      </div>
      <div class="form-group row">
        <label for="visitingHours" class="col-sm-3 col-form-label">
          Visiting Hours
        </label>
        <div class="col-sm-9">
          <input id="id_visitingHours" type="string" name="visitingHours" placeholder="Visiting Hours"
            class="form-control" maxlength="20" autofocus required>
        </div>
      </div>
      <span id="id_error"></span>
      <span id="id_success"></span>
      <button type="submit" class="btn btn-primary btn-block">Register</button>
    </form>
    <!-- /form -->
  </div>

</body>
{% endblock %}
{% block extrajavascripts %}
  <script type="text/javascript" src="{% static 'p2preview/js/signup.js' %}"/>
  <script>

  </script>
{% endblock %}